### ISSUE TITLE
Questions about Framework

### ISSUE THREAD

**Issue by ziomek64** [nightlybuilds-net/Xam.Zero#7]
Hi, 
I'd like to try this framework but have some questions beforehand.

Are you planning to support it in long term and possibly support maui?

Does it support routes? Example I have login route with one page and main route with tabbar consisting of three pages. When navigating I just type //login or //main. How is it working here?

Will it work fine with community toolkit? Especially wondering about popups and  passing objects to them, coming back with a result

Will it work with like nested pages and their viewmodels? Example I have media details page and related medias to that one and I want to user to go there and again deeper infinitely and go back one by one.

Is it working with newest xamarin versions?

What are the limitations of this framework or is only expanding what Shell can do

Really like the idea of your framework. That's like the only one I've found that supports Shell sadly. Current Shell is limited when passing complex strings. It messes them up for me

**Comment by markjackmilian** [comment]
> So nothing is working from toolkit or rather stuff related to navigation? Community toolkit has some touch effects, bindable commands to them, converters etc.
> 
> In the meantime is there something that will allow me to await push the page to wait for some sort of a result from that page? I want to push the page, select something on that new page and come back with selected object. That's what I can do now but I'll need workaround for stuff like this. Instead of using a popup I'll use a page

Hi,
touch effects, commands, converters from community are not related with the usage of the framework. So, yes you can use all the community toolkit functionalities.

To retrieve data when you came back from a page you can use ReverseInit(object obj) method on first viewmodel.
VM1 push Page2 with VM2
VM2 do something and POP Page2 passing object
VM1 receive the object in ReverseInit method

**Comment by markjackmilian** [comment]
> @markjackmilian The sample app could use some update. I'm trying to follow it some stuff are not working at least out of the box.
> 
> ```
> public App()
>         {
>             InitializeComponent();
> 
>             ZeroApp.On(this)
>                 .WithContainer(DryIocZeroContainer.Build(dryIocContainer: new DryIoc.Container()))
>                 .RegisterShell(() => new AppShell())
>                 .StartWith<AppShell>();
>         }
> ```
> 
> This is how I register shell, with the container. I'm confused about container part as your code was not working and I don't know if mine is correct. [AddINotifyPropertyChangedInterface] attribute seems to be not working for me for my viewmodel, I tried adding all namespaces as you do. And my Viewmodel derives from ZeroBaseModel. I don't even know where you get that PropertyChanged namespace from.
> 
> ```
>     using PropertyChanged;
> ```
> 
> The guide would need some update or better, make an update for sample app as from what I see this one is 2 years old. Even if you answer me some people still might need help that's why it would be better to update documentation a bit and sample app. Please make sure that these are updated for newest xamarin forms versions

Hi,

sample app is working correctly for me.
Please create a container outside and use it like so:
```
public static Container DryContainer = new DryIoc.Container();
public App()
        {
            InitializeComponent();

            ZeroApp.On(this)
                .WithContainer(DryIocZeroContainer.Build(DryContainer))
                .RegisterShell(() => new AppShell())
                .StartWith<AppShell>();
        }
```
otherwise you will have no way to use the container.
The [AddINotifyPropertychanged] is not related with Xam.Zero. It is part of PropertyChanged.Fody.

**Comment by ziomek64** [comment]
Everything I think is working for me, at least for now. But I noticed one weird thing, I don't know if this is a bug. I push the page like this - 

`Push<MediaDetailsPage>(SelectedAnimeMedia, false);`

SelectedAnimeMedia is of my type Media. Then on that second viewmodel I receive the object - 

```
        protected override void PrepareModel(object data)
        {
            CurrentMedia = (Media)data;
            base.PrepareModel(data);
        }
```

I set the breakpoint on the CurrentMedia = (Media)data. And what happens is that this breakpoint is hit two times, first time with null then with my actual data. This is only when I go to that page first time. The second time this breakpoint will hit one time with my data. Is this first time going to that page and hitting breakpoint two times a bug?

**Comment by markjackmilian** [comment]
I haven't noticed this kind of behavior in my projects. I'm going to take a closer look at it.
Do you have an example where this error occur?

**Comment by ziomek64** [comment]
I do not have an example , this happens in my personal project. I might create sample project in the evening. I don't know why is this happening. I've tested that my task with push happens only one  time in my first viewmodel. But the PrepareModel runs two times the first time. Null, and data. Then it works fine and runs through one time. I will try making a sample, maybe this is only on my end, I don't know. 

Let me know if you test it first

**Comment by ziomek64** [comment]
@markjackmilian try this repo https://github.com/ziomek64/SimpleTabbedAppPushTest
I modified your sample app, with additional button on homepage that will lead to new page with object. Try putting a breakpoint inside PrepareModel in that new page viewmodel. I also created small Person class.

Please just copy folders as I haven't made any deployment options. I cloned your repo, modified it, and just copied files to my repo. So you need HomePage, HomePageViewModel , TestPushPage, TestPushPageViewModel, and PersonClass

**Comment by ziomek64** [comment]
@markjackmilian Can you provide info what 1.3.0 changed?

**Comment by markjackmilian** [comment]
Thank you for your feedback, I'll add a release change log in few hours.

**Comment by markjackmilian** [comment]
> @markjackmilian Can you provide info what 1.3.0 changed?

We introduced an abstraction to support navigation to popups.
We support RGPopUp and XCToolkit Popup, you can find an example on the Xam.Zero.SimpleTabbedApp project.

We will add documentation soon.

**Comment by ziomek64** [comment]
@markjackmilian no info about the bug I had? I provided testing app

**Comment by markjackmilian** [comment]
I'll look into it later this week.
